### ISSUE TITLE
Calcul du centroid pour les polyhèdres

### ISSUE THREAD

**Issue by BenPinier** [FractoryLabcom/software#3]
Le calcul du centroid est actuellement défaillant pour des figures comme pyramides ou cube. Les autres méthodes de polyèdres sont fonctionnelles.

**Comment by BenPinier** [comment]
Modification de la méthode d'intégration sur les triangles par une intégration point milieu. Les résultats semblent corrects. A approfondir.
Le calcul du volume est aussi corrigé.

**Comment by BenPinier** [comment]
La méthode ComputeSize est elle aussi modifiée. Son implémentation étaient juste si le centre de gravité coupait tous les segments passant par lui en leurs milieux. Ce qui n'est pas le cas pour les pyramides.

L'algorithme est remplacé par un algo brute-force en O(N^2) au lieu de O(N) en attendant mieux.

**Comment by rlegoc** [comment]
ça semble bon,
